using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PureRpc.Generator;

[Generator]
public class PureRpcGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serviceDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) => GetServiceMetadata(ctx))
            .Where(m => m is not null);

        context.RegisterSourceOutput(serviceDeclarations, (spc, metadata) =>
        {
            if (metadata == null) return;
            // 生成器运行在编译期，StringBuilder/SourceText 的分配不会进入业务运行时热路径。
            // 改进建议：若接口数量很多，可继续保持增量生成输入足够精细，避免无关文件变更触发大量重新生成。
            spc.AddSource($"{metadata.InterfaceName}.g.cs", SourceText.From(GenerateSource(metadata), Encoding.UTF8));
        });
    }

    private ServiceMetadata? GetServiceMetadata(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not InterfaceDeclarationSyntax interfaceDecl) return null;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(interfaceDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        // 匹配简化后的属性名 RpcServiceAttribute
        var serviceAttr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "RpcServiceAttribute");
        if (serviceAttr == null) return null;

        var metadata = new ServiceMetadata
        {
            Namespace = symbol.ContainingNamespace.ToDisplayString(),
            InterfaceName = symbol.Name,
            ServiceName = serviceAttr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? symbol.Name,
            Methods = new List<MethodMetadata>()
        };

        foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
        {
            // 匹配简化后的属性名 RpcMethodAttribute
            var methodAttr = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "RpcMethodAttribute");
            if (methodAttr == null) continue;

            var attrMethodName = methodAttr.ConstructorArguments.FirstOrDefault().Value?.ToString();
            var protocolMethodName = string.IsNullOrEmpty(attrMethodName) ? member.Name : attrMethodName;

            var payloadParam = member.Parameters.FirstOrDefault(p =>
                p.Type.ToDisplayString() != "System.Threading.CancellationToken" &&
                p.Type.ToDisplayString() != "CancellationToken");

            bool hasCt = member.Parameters.Any(p =>
                p.Type.ToDisplayString() == "System.Threading.CancellationToken" ||
                p.Type.ToDisplayString() == "CancellationToken");

            bool isVoid = member.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task" ||
                          member.ReturnType.ToDisplayString() == "System.Threading.Tasks.ValueTask" ||
                          member.ReturnType.ToDisplayString() == "void";

            string responseType = "object";
            if (member.ReturnType is INamedTypeSymbol namedType && namedType.IsGenericType)
                responseType = namedType.TypeArguments[0].ToDisplayString();

            metadata.Methods.Add(new MethodMetadata
            {
                ProtocolMethodName = protocolMethodName!,
                SourceMethodName = member.Name,
                FullReturnType = member.ReturnType.ToDisplayString(),
                ResponseType = responseType,
                RequestType = payloadParam?.Type.ToDisplayString() ?? "bool",
                IsVoid = isVoid,
                HasPayload = payloadParam != null,
                HasCancellationToken = hasCt
            });
        }
        return metadata;
    }

    private string GenerateSource(ServiceMetadata m)
    {
        var proxyName = $"{m.InterfaceName}Proxy";
        var dispatcherName = $"{m.InterfaceName}Dispatcher";
        var serviceShortName = m.InterfaceName.StartsWith("I") ? m.InterfaceName.Substring(1) : m.InterfaceName;

        // 编译期拼接生成代码使用 StringBuilder，避免大量字符串 + 带来的中间字符串分配。
        // 这些分配发生在编译期，不影响 RPC 调用时延。
        var sb = new StringBuilder();
        sb.AppendLine($$"""
// <auto-generated/>
using System;
using System.Buffers;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using PureRpc;
using PureRpc.Abstractions;

namespace {{m.Namespace}}
{
    internal sealed class {{proxyName}} : {{m.InterfaceName}}
    {
        private readonly IRpcClient _client;
        private readonly ISerializer _serializer;

        public {{proxyName}}(IRpcClient client, ISerializer serializer) 
        {
            _client = client;
            _serializer = serializer;
        }

""");

        foreach (var method in m.Methods)
        {
            var args = new List<string>();
            if (method.HasPayload) args.Add($"{method.RequestType} request");
            if (method.HasCancellationToken) args.Add("CancellationToken ct = default");
            string paramsStr = string.Join(", ", args);

            sb.AppendLine($$"""
        public async {{method.FullReturnType}} {{method.SourceMethodName}}({{paramsStr}})
        {
            var argWriter = new ArrayBufferWriter<byte>(128);
            {{(method.HasPayload ? "_serializer.Serialize(argWriter, request);" : "// No payload")}}

            var responseBytes = await _client.CallAsync("{{m.ServiceName}}", "{{method.ProtocolMethodName}}", 
                new ReadOnlySequence<byte>(argWriter.WrittenMemory), {{(method.HasCancellationToken ? "ct" : "default")}});
            
            {{(method.IsVoid ? "return;" : $"return _serializer.Deserialize<{method.ResponseType}>(responseBytes);")}}
        }
""");
        }

        sb.AppendLine($$"""
    }

    internal sealed class {{dispatcherName}} : IServiceDispatcher
    {
        public string ServiceName => "{{m.ServiceName}}";
        
        private readonly {{m.InterfaceName}} _service;
        private readonly ISerializer _serializer;

        public {{dispatcherName}}({{m.InterfaceName}} service, ISerializer serializer) 
        {
            _service = service;
            _serializer = serializer;
        }

        public async ValueTask DispatchAsync(string methodName, ReadOnlySequence<byte> payload, RpcContext context)
        {
            var __baseService = _service as ServiceBase;
            if (__baseService != null) __baseService.Context = context;

            try
            {
                switch (methodName)
                {
""");

        foreach (var method in m.Methods)
        {
            var callArgsList = new List<string>();
            if (method.HasPayload) callArgsList.Add("req");
            if (method.HasCancellationToken) callArgsList.Add("context.CancellationToken");
            string callParamsStr = string.Join(", ", callArgsList);

            sb.AppendLine($$"""
                    case "{{method.ProtocolMethodName}}":
                        {
                            {{(method.HasPayload ? $"// 反序列化会分配请求 DTO；可通过紧凑 DTO/值类型字段减少热路径对象数量。\n                            var req = _serializer.Deserialize<{method.RequestType}>(payload);" : "")}}
                            {{(method.IsVoid ? "" : "var res = ")}}await _service.{{method.SourceMethodName}}({{callParamsStr}});
                            {{(method.IsVoid ? "" : "// 响应直接写入 RpcContext 的池化缓冲，避免额外 byte[] 中转。")}}
                            {{(method.IsVoid ? "" : "_serializer.Serialize(context.ResponseBuffer, res);")}}
                            break;
                        }
""");
        }

        sb.AppendLine($$"""
                    default:
                        throw new RpcException($"Method '{methodName}' not found in service {{m.ServiceName}}");
                }
            }
            finally
            {
                if (__baseService != null) __baseService.Context = null!;
            }
        }
    }

    public static partial class {{m.InterfaceName}}Extensions
    {
        public static IServerBuilder With{{serviceShortName}}<TImplementation>(this IServerBuilder builder)
            where TImplementation : class, {{m.InterfaceName}}
        {
            builder.Services.AddSingleton<{{m.InterfaceName}}, TImplementation>();
            builder.Services.AddSingleton<IServiceDispatcher>(sp => 
            {
                var impl = sp.GetRequiredService<{{m.InterfaceName}}>();
                var serializer = sp.GetRequiredService<ISerializer>();
                return new {{dispatcherName}}(impl, serializer);
            });
            return builder;
        }

        public static IClientBuilder With{{serviceShortName}}Proxy(this IClientBuilder builder)
        {
            builder.Services.AddSingleton<{{m.InterfaceName}}>(sp => 
            {
                var client = sp.GetRequiredService<IRpcClient>();
                var serializer = sp.GetRequiredService<ISerializer>();
                return new {{proxyName}}(client, serializer);
            });
            return builder;
        }
    }
}
""");

        return sb.ToString();
    }

    private class ServiceMetadata { public string Namespace = null!; public string InterfaceName = null!; public string ServiceName = null!; public List<MethodMetadata> Methods = null!; }
    private class MethodMetadata
    {
        public string ProtocolMethodName = null!;
        public string SourceMethodName = null!;
        public string FullReturnType = null!;
        public string ResponseType = null!;
        public string RequestType = null!;
        public bool IsVoid;
        public bool HasPayload;
        public bool HasCancellationToken;
    }
}
